services:
  yt-music-downloader:
    container_name: yt_subs
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./output:/music
      - ./config:/app/config
      - ./app:/app/app
    restart: unless-stopped
