services:
  yt-subs:
    container_name: yt_subs
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000"
    environment:
      - TZ=Europe/Madrid
      - YT_COMMAND=boot
    volumes:
      - /mnt/nextcloud_hdd_1/Navidrome/music:/music
      - ./config:/Workspace/config
      - ./data:/Workspace/data
      - ./src:/Workspace/src
      - /mnt/nextcloud_hdd_1/Navidrome/temp:/Workspace/temp
    restart: unless-stopped
